---
title: "Regular Expressions (Regex)"
author: "HD Sheets" 
date: "2024-10-01"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Regular Expressions

This is a method of specifying patterns to search for in text.  It is used in
R, Python, SQL and many other places.   It works pretty much the same in all of
the places it appears.

Learning to write regex search patterns takes a while, it's kind of a puzzle 
solving problem.

Tinkering with it a bit,  it looks like ChatGPT does pretty well at figuring out
regex patterns.  But they don't always seem to work, so one needs to be careful.
They did show some interesting ideas or methods in the ChatGPT output though.

See chapter 15 of Wickham et al

```{R}
library(tidyverse)
library(babynames)
library(stringr)

```

# str_view

Str_view seems to be a tool largely for figuring out how a regex expression is working

It often takes a bit of tinkering to figure out hwo to write a good search target
using regex,  sort of testing as you go.  str_view() seems to help with that

Prints out the section of each string found with the target in it

fruit is a list of names of 80 fruits

```{R}
str_view(fruit,"berry")
```

## *Question/Action*

try this with apple and star

# combinations and wild cards

a.  means a followed by any number of characters or white space

the period is a "wildcard" for any character

```{R}
str_view(c("a","ab","a:b","ed"," a b","eab"),"a.")
```
All fruits with an "a", then any 3 letters, then an "e"

```{R}
str_view(fruit,"a...e")
```

to find a period "." we use an escapte sequence "\\."

```{R}
str_view("Go, no Stop.Don't Stop","\\.")
```

## Quantifiers-

How many times does the pattern have to appear

? - makes a pattern option,  so "ab?" is an an "a" followed by or or 1 b,  ie "a", "ab"

+ means "one or more"  so "ab+" matches   "ab", "abb", "abbb"  etc

{}- indicates a range "ab{2,4}" means a plus two to four "b"s,  abb, abbb,abbbb

[[:digit:]]- means a digit,  so [[:digit:]]{1,3}  means 1 tp 3 digits in a row

```{R}
str_view(fruit,"ba?")

```
## Character classes

We can define a set of characters to use in a match
[abcde]

```{R}
str_view(fruit,"[abcde]{2,4}")
```
## OR operation

"(a|b)"- a or b

"(aa|ee|ii|oo|uu)"- doubled consonant

```{R}
str_view(fruit,"(aa|ee|ii|oo|uu)")
```
## Major functions

Find a target in a large number of strings.

The function to do this is

  str_detect

Say fruits that start with "a"

I got the search target from ChatGPT

        "\b[aA]\W*"

which means a blank \b,   followed by an upper or lower case a, then any word type item
of any length

The original version did not work, I had to tweak it a bit.   Expect to have to
tweak chatGPT outpus

```{R}
str_detect(fruit,"\\b[aA]\\W*")
```

we can print this out

```{R}
fruit[str_detect(fruit,"\\b[aA]\\W*")]
```
I probably would have used

"^(a|A)" -  which is "a string that starts with a or A"

```{R}
fruit[str_detect(fruit,"^(a|A)")]
```


## Replace values

str_replace() and str_replace_all

```{R}
x <- c("apple", "pear", "banana")
str_replace_all(x, "[aeiou]", "*")
```

## Parsing a column in a data frame

One problem you will see a lot is breaking up a column that has multiple
items or values in a single column of text


Here is an example

```{R}
df <- tribble(
  ~str,
  "<Sheryl>-F_34",
  "<Kisha>-F_45", 
  "<Brandon>-N_33",
  "<Sharon>-F_38", 
  "<Penny>-F_58",
  "<Justin>-M_41", 
  "<Patricia>-F_84", 
)

```

```{R}
df
```

We want the name, gender and age from this single column of text

There are delimiters, which we want to remove

<              - first delimite
[[A-Za-z]]+    - text, no spaces, any number of text
>-            -second delimiter, two pieces
(N|n|F|F|M|m)   -gender,  we could use . here as well
_               -delimiter between our gender and age
[0-9]{1,3}       -age,  1 to 3 digits

Since this is a common task, there is a tidyverse tool that will do this
in one step

sepearate_wider_regex(string, patterns)

patterns is a vector c(),  and all named patterns are stored in the extracted
data

patterns with no names are dropped

```{R}

separate_wider_regex(df,
        str,
        patterns=c(
                    "<", 
                    name = "[[:alpha:]]+", 
                    ">-",
                    gender = ".",
                     "_",
                    age = "[[:digit:]]+"
          )
)
```


## separate_wider_delim

There is also a delimiter based splitter

it allows only one possible delimiter between values,  so it is not as
flexible as separate_wider_regex

```{R}

df2=data.frame(str=c(
  "Smith,Bob",
  "Jones, Sar",
  "Kim, Amanda")
  )


separate_wider_delim(df2,
                     str,
                     delim=",",
                     names=c("last","first")
                     )

```

